### ISSUE TITLE
[Question] Adding curve as constraint

### ISSUE THREAD

**Issue by praneethw** [uqfoundation/mystic#93]
Based on a post available on stackoverflow, we are trying to utilize mystic to solve a global optimization problem, but having trouble trying to fit the required constrains to the library. Appreciate if you could look at the problem listed below and provide some guidance to solve our problem.

objective function 
Minimize
![image](https://user-images.githubusercontent.com/13520386/28057498-0122b0ee-663e-11e7-9689-3243d0294c4b.png)
(P is the slack variable) 
 
constraints:
![image](https://user-images.githubusercontent.com/13520386/28061082-dc35fb16-6646-11e7-9d37-6e3920ae641c.png)

sample python code that we have use

```
from mystic.solvers import diffev2
from mystic.penalty import quadratic_inequality
from mystic.monitors import VerboseMonitor
import numpy as np

C = 221
Q = 500
production = 1000

x0 = [0.0, 0.0, 0.0, 0.0]
bounds = [(0,5), (0,4), (0,3), (0,None)]
#x[3] is the slack variable

def func_value(d):  
        curve_vec=[]
        for val in d:
            curve = (0.3 * val) + ((2 * (val ** (3/2))) / 3)
            curve_vec.append(curve)
        return curve_vec

def func(x):
        curve = func_value(x[0:3])
        return -(sum(np.dot(curve,production))-Q+x[3])

objective = lambda x: sum(np.dot(x[0:3],C))+1000*x[3]     

constraint = lambda x: func(x)

@quadratic_inequality(constraint)
def penalty(x):
  return 0.0

solution = diffev2(objective,x0,penalty=penalty,bounds=bounds)
print(solution)
```

Please do let us know if we are passing in the constraints as is expected to our problem, else how we should pass them in to the library.

**Comment by mmckerns** [comment]
That's correct.  You are applying your constraints in the traditional method, as penalties.  If you tweak some of the solver parameters, you can see you get a better answer then you are with your code.

```
from mystic.solvers import diffev2, fmin_powell
from mystic.penalty import quadratic_inequality
from mystic.monitors import VerboseMonitor
from mystic.constraints import as_constraint
import numpy as np

C = 221
Q = 500
production = 1000

x0 = [0.0, 0.0, 0.0, 0.0]
bounds = [(0,5), (0,4), (0,3), (0,None)]
#x[3] is the slack variable

def func_value(d):
    curve_vec=[]
    for val in d:
        curve = (0.3 * val) + ((2 * (val ** (3/2))) / 3)
        curve_vec.append(curve)
    return curve_vec

def func(x):
    curve = func_value(x[0:3])
    return -(sum(np.dot(curve,production))-Q+x[3])

objective = lambda x: sum(np.dot(x[0:3],C))+1000*x[3]

constraint = lambda x: func(x)

@quadratic_inequality(constraint)
def penalty(x):
    return 0.0

solver = as_constraint(penalty)


mon = VerboseMonitor(50)
solution = diffev2(objective,x0,penalty=penalty,bounds=bounds,itermon=mon,gtol=100, maxiter=1000, maxfun=10000, npop=40)
print(solution)
mon = VerboseMonitor(50)
solution = fmin_powell(objective,x0,penalty=penalty,bounds=bounds,itermon=mon,gtol=100, maxiter=1000, maxfun=10000)
print(solution)
```

`mystic` can also apply the constraints as "operators" (or kernel transformations, if you prefer to think of them in those terms).  They are applied in this way with the `constraints` keyword.  You can see examples of how to do so in the `examples2` directory.  To use them, you either have to do a little more work to figure out how to build an appropriate kernel transform, or you have to live with a pretty big performance hit.

**Comment by praneethw** [comment]
Related to the same question, when we giving x0 as zero vector (x0=[0,0,0,0]), “fmin_powell” doesn’t give the global minimum as our solution. Is there any reason for that?.  or do we have to tweak some parameters.

**Comment by mmckerns** [comment]
Powell is a local minimizer, not a global minimizer.  So, if you are in the region of a local minimum, if might get stuck there instead of at the global minimum.  Powell just moves downhill, so it's very likely it will fail unless x0 is in the neighborhood of the global minimum.  Penalty functions don't stop the optimizer from selecting "bad" values... they just penalize "bad" values, so you can still get stuck in a local minimum even if the constraints say it's a "bad" value.  If you want to guarantee that the constraints are satisfied, you would need to apply a kernel transformation (i.e. an operator) -- however, this still doesn't guarantee finding the global minimum, if there are local minima that also satisfy the constraints.  So, yes, typically you keep "tweaking" optimizer parameters until you find the best solution, and can convince yourself that you have the global minimum.  You might also want to try mystic's ensemble optimizers or global search tools.  Again, check the examples, looking for keywords "ensemble" and/or "search".
